### ISSUE TITLE
Build Training Page - Hero

### ISSUE THREAD

**Issue by JayeshVP24** [tcet-opensource/tnp-website#10]
- [ ] title
- [ ] carousel
- [ ] event cards

**Comment by JayeshVP24** [comment]
create new file in pages called `training.astro`
and import your component in this file to display it

**Comment by riyavishwa981** [comment]
good work just figure out this problem
![image](https://user-images.githubusercontent.com/79577834/230729915-9c61f4bb-bc32-4305-a962-a0ec39649e4b.png)
