### ISSUE TITLE
Add contributers list

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/tnp-website#12]
This is a beginner task that anyone outside the organization can attempt. The steps to complete the task are listed below.

- [ ] Go through the branches and note down how many members have contributed to the code base. 
- [ ] Create CONTRIBUTORS.md in staging branch
- [ ] List down all contributors names in alphabetical order (please make sure you create a proper list)
- [ ] Push your file to staging

**Comment by demonkillerr** [comment]
If you would like to contribute to this repository via this issue, please comment your Github username below so that we can assign this task to you.

**Comment by Wmg20** [comment]
I will do this

**Comment by Wmg20** [comment]
Could you please check the PR and let me know if it is okay, or if it needs any changes?

**Comment by demonkillerr** [comment]
Solved by @Wmg20 in #56. 

UI TEAM list is here.
