### ISSUE TITLE
Add UI/UX contributors in CONTRIBUTERS.md

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/tnp-website#57]
This is a beginner task that anyone outside the organization can attempt. The steps to complete the task are listed below.

- [ ] Navigate to #56 
- [ ] Find UI team members who contributed to the design. The list is mentioned by @kuxshl 
- [ ] Add these members in CONTRIBUTORS.md
- [ ] Push your file to staging

While creating a PR, kindly mention this issue's no (#57) on your PR

**Comment by DustyDogCodex** [comment]
Hi!

If no one else has been assigned, I can complete this issue for you right now.
