### ISSUE TITLE
Build Testimonials

### ISSUE THREAD

**Issue by JayeshVP24** [tcet-opensource/tnp-website#8]
- [ ] Student testimonial Carousel
- [ ] Company Testimonial Carousel
- [ ] Responsive

**Comment by riyavishwa981** [comment]
I'm not sure if I am correct or not but can we create a function so that we do not have to rewrite the same code for student testimonial as well as company testimonial . Can we do something to optimize the code?

**Comment by JayeshVP24** [comment]
do a `git pull origin 8-build-testimonials`
I have made some changes

**Comment by JayeshVP24** [comment]
`

> I'm not sure if I am correct or not but can we create a function so that we do not have to rewrite the same code for student testimonial as well as company testimonial . Can we do something to optimize the code?

He has done that.

**Comment by riyavishwa981** [comment]
ok got it

**Comment by riyavishwa981** [comment]
looks good
