### ISSUE TITLE
[FEATURE] - Changes in footer design

### ISSUE THREAD

**Issue by Neeharikajha** [tcet-opensource/tnp-website#83]
### Describe the improvement

Current Design :
![image](https://github.com/tcet-opensource/tnp-website/assets/136990222/49d239a0-10e3-4680-9180-93b65febfd67)

Expected Design:
![image](https://github.com/tcet-opensource/tnp-website/assets/136990222/a1531ad9-80d9-4954-a456-28d13728e389)

### Why do we need this?

Improvement in the overall frontend.

### Do you have a proposed solution?

Possible Changes:

1. Move the 'contact and copyright' section to the left and the nav-bar links to the right
2. Left-align the nav-bar links from the footer section. 

Refer the Figma design for better understanding.

### Do you want to work on this feature?

- [ ] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by sudhanshu-28** [comment]
Could you please assign this issue to me?
